---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: task-manager-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: task-manager-repo
  policy:
    semver:
      range: 0.1.x
