---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: task-manager-github-source
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: main
  secretRef:
    name: flux-github-deploy-key
  url: ssh://git@github.com/armanharut98/backend_task_manager.git
